In [ ]:
!pip install torch torchvision


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [2]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,requires_grad=False)
print(float_32_tensor)

tensor([3., 6., 9.])


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) 
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8656, 0.9469],
        [0.6098, 0.3547]]) 



In [4]:
rand_tensor = torch.rand((2,3))
print(rand_tensor)

tensor([[0.3802, 0.4935, 0.2281],
        [0.5534, 0.6164, 0.0090]])


In [5]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

reshaped = tensor.reshape(3, 2)

print("Original Tensor:\n", tensor)
print("Reshaped Tensor:\n", reshaped)


Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped Tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

stacked = torch.stack((tensor1, tensor2))

print("Stacked Tensor:\n", stacked)

stacked_dim1 = torch.stack((tensor1, tensor2), dim=1)
print("Stacked Along Dimension 1:\n", stacked_dim1)


Stacked Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Stacked Along Dimension 1:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
tensor = torch.tensor([[[1, 2, 3]]])  

squeezed = torch.squeeze(tensor)  

print("Original Tensor Shape:", tensor.shape)
print("Squeezed Tensor Shape:", squeezed.shape)
print("Squeezed Tensor:", squeezed)


Original Tensor Shape: torch.Size([1, 1, 3])
Squeezed Tensor Shape: torch.Size([3])
Squeezed Tensor: tensor([1, 2, 3])


In [ ]:
tensor = torch.tensor([1, 2, 3])  

unsqueezed = torch.unsqueeze(tensor, dim=0)  

print("Original Tensor Shape:", tensor.shape)
print("Unsqueezed Tensor Shape:", unsqueezed.shape)
print("Unsqueezed Tensor:\n", unsqueezed)

unsqueezed_dim1 = torch.unsqueeze(tensor, dim=1)  
print("Unsqueezed Along Dimension 1 Shape:", unsqueezed_dim1.shape)


Original Tensor Shape: torch.Size([3])
Unsqueezed Tensor Shape: torch.Size([1, 3])
Unsqueezed Tensor:
 tensor([[1, 2, 3]])
Unsqueezed Along Dimension 1 Shape: torch.Size([3, 1])


In [ ]:
tensor = torch.randn(2, 3, 4)

permuted = tensor.permute(1, 0, 2)  

print("Original Tensor Shape:", tensor.shape)
print("Permuted Tensor Shape:", permuted.shape)


Original Tensor Shape: torch.Size([2, 3, 4])
Permuted Tensor Shape: torch.Size([3, 2, 4])


In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element = tensor[1, 2]  
print("Single Element:", element)  

row = tensor[1]  
print("Row 1:", row)  

column = tensor[:, 2]  
print("Column 2:", column)  

sub_tensor = tensor[0:2, 1:3]  
print("Sliced Tensor:\n", sub_tensor)  


Single Element: tensor(6)
Row 1: tensor([4, 5, 6])
Column 2: tensor([3, 6, 9])
Sliced Tensor:
 tensor([[2, 3],
        [5, 6]])


In [ ]:
rows = torch.tensor([0, 2])
selected_rows = tensor[rows]
print("Selected Rows:\n", selected_rows)  

indices = torch.tensor([0, 2])
selected_elements = tensor[1, indices]  
print("Selected Elements:", selected_elements)  


Selected Rows:
 tensor([[1, 2, 3],
        [7, 8, 9]])
Selected Elements: tensor([4, 6])


In [ ]:
mask = tensor > 5
print("Boolean Mask:\n", mask)  

filtered = tensor[mask]
print("Filtered Elements:", filtered)  


Boolean Mask:
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Filtered Elements: tensor([6, 7, 8, 9])


In [ ]:
rows = torch.tensor([0, 2])
cols = torch.tensor([1, 2])
selected = tensor[rows, cols]  
print("Fancy Indexed Elements:", selected)  


Fancy Indexed Elements: tensor([2, 9])


In [ ]:
selected_rows = torch.index_select(tensor, dim=0, index=torch.tensor([0, 2]))
print("Selected Rows:\n", selected_rows)  

selected_columns = torch.index_select(tensor, dim=1, index=torch.tensor([0, 2]))
print("Selected Columns:\n", selected_columns)  


Selected Rows:
 tensor([[1, 2, 3],
        [7, 8, 9]])
Selected Columns:
 tensor([[1, 3],
        [4, 6],
        [7, 9]])
