In [ ]:
!pip install torch torchvision


In [6]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Create a PyTorch tensor
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [2]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,requires_grad=False)
print(float_32_tensor)

tensor([3., 6., 9.])


In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8656, 0.9469],
        [0.6098, 0.3547]]) 



In [4]:
rand_tensor = torch.rand((2,3))
print(rand_tensor)

tensor([[0.3802, 0.4935, 0.2281],
        [0.5534, 0.6164, 0.0090]])


In [5]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [6]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [3]:


# Create a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape it to a 3x2 tensor
reshaped = tensor.reshape(3, 2)

print("Original Tensor:\n", tensor)
print("Reshaped Tensor:\n", reshaped)


Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped Tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [4]:
# Create two tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Stack along a new dimension (default: dim=0)
stacked = torch.stack((tensor1, tensor2))

print("Stacked Tensor:\n", stacked)

# Stack along the second dimension (dim=1)
stacked_dim1 = torch.stack((tensor1, tensor2), dim=1)
print("Stacked Along Dimension 1:\n", stacked_dim1)


Stacked Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Stacked Along Dimension 1:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [6]:


# Create a tensor with singleton dimensions
tensor = torch.tensor([[[1, 2, 3]]])  # Shape: (1, 1, 3)

# Squeeze the tensor
squeezed = torch.squeeze(tensor)  # Shape becomes (3,)

print("Original Tensor Shape:", tensor.shape)
print("Squeezed Tensor Shape:", squeezed.shape)
print("Squeezed Tensor:", squeezed)


Original Tensor Shape: torch.Size([1, 1, 3])
Squeezed Tensor Shape: torch.Size([3])
Squeezed Tensor: tensor([1, 2, 3])


In [7]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])  # Shape: (3,)

# Unsqueeze to add a dimension at position 0
unsqueezed = torch.unsqueeze(tensor, dim=0)  # Shape: (1, 3)

print("Original Tensor Shape:", tensor.shape)
print("Unsqueezed Tensor Shape:", unsqueezed.shape)
print("Unsqueezed Tensor:\n", unsqueezed)

# Unsqueeze to add a dimension at position 1
unsqueezed_dim1 = torch.unsqueeze(tensor, dim=1)  # Shape: (3, 1)
print("Unsqueezed Along Dimension 1 Shape:", unsqueezed_dim1.shape)


Original Tensor Shape: torch.Size([3])
Unsqueezed Tensor Shape: torch.Size([1, 3])
Unsqueezed Tensor:
 tensor([[1, 2, 3]])
Unsqueezed Along Dimension 1 Shape: torch.Size([3, 1])


In [8]:
# Create a tensor with shape (2, 3, 4)
tensor = torch.randn(2, 3, 4)

# Permute dimensions: swap axes 0 and 1
permuted = tensor.permute(1, 0, 2)  # Shape becomes (3, 2, 4)

print("Original Tensor Shape:", tensor.shape)
print("Permuted Tensor Shape:", permuted.shape)


Original Tensor Shape: torch.Size([2, 3, 4])
Permuted Tensor Shape: torch.Size([3, 2, 4])


In [7]:
#basic indexing

# Create a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select a single element
element = tensor[1, 2]  # Element at row 1, column 2
print("Single Element:", element)  # Output: 6

# Select a specific row
row = tensor[1]  # Second row
print("Row 1:", row)  # Output: [4, 5, 6]

# Select a specific column
column = tensor[:, 2]  # Third column
print("Column 2:", column)  # Output: [3, 6, 9]

# Slice rows and columns
sub_tensor = tensor[0:2, 1:3]  # Rows 0-1, Columns 1-2
print("Sliced Tensor:\n", sub_tensor)  # Output: [[2, 3], [5, 6]]


Single Element: tensor(6)
Row 1: tensor([4, 5, 6])
Column 2: tensor([3, 6, 9])
Sliced Tensor:
 tensor([[2, 3],
        [5, 6]])


In [8]:
#advanced indexing
# Select specific rows using a tensor
rows = torch.tensor([0, 2])
selected_rows = tensor[rows]
print("Selected Rows:\n", selected_rows)  # Output: [[1, 2, 3], [7, 8, 9]]

# Select specific elements with tensor indexing
indices = torch.tensor([0, 2])
selected_elements = tensor[1, indices]  # Row 1, Columns 0 and 2
print("Selected Elements:", selected_elements)  # Output: [4, 6]


Selected Rows:
 tensor([[1, 2, 3],
        [7, 8, 9]])
Selected Elements: tensor([4, 6])


In [9]:
#boolean indexing
# Create a boolean mask
mask = tensor > 5
print("Boolean Mask:\n", mask)  # True where elements > 5

# Select elements that satisfy the condition
filtered = tensor[mask]
print("Filtered Elements:", filtered)  # Output: [6, 7, 8, 9]


Boolean Mask:
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Filtered Elements: tensor([6, 7, 8, 9])


In [10]:
#fancy indexing
# Select specific elements using row and column indices
rows = torch.tensor([0, 2])
cols = torch.tensor([1, 2])
selected = tensor[rows, cols]  # (0,1) and (2,2)
print("Fancy Indexed Elements:", selected)  # Output: [2, 9]


Fancy Indexed Elements: tensor([2, 9])


In [11]:
#selecting along dimension
# Select specific rows (dim=0)
selected_rows = torch.index_select(tensor, dim=0, index=torch.tensor([0, 2]))
print("Selected Rows:\n", selected_rows)  # Output: [[1, 2, 3], [7, 8, 9]]

# Select specific columns (dim=1)
selected_columns = torch.index_select(tensor, dim=1, index=torch.tensor([0, 2]))
print("Selected Columns:\n", selected_columns)  # Output: [[1, 3], [4, 6], [7, 9]]


Selected Rows:
 tensor([[1, 2, 3],
        [7, 8, 9]])
Selected Columns:
 tensor([[1, 3],
        [4, 6],
        [7, 9]])
